---
title: "League of Legends"
output: html_document
---

```{r echo=FALSE, message=FALSE, warning=FALSE, "0.1 packages"}

library(ggplot2)
library(bitops)
library(RCurl)
library(ggthemes)
library(foreign)
library(grid)
library(RColorBrewer)
library(gridExtra)
library(reshape2)
library(stringr)
library(scales)
library(dplyr)
library(GGally)
library(memisc)
library(lattice)
library(MASS)
```

```{r "0.2 Load_the_Data"}
# Source: https://www.kaggle.com/chuckephron/leagueoflegends
getwd()

# PC:
setwd('C:/Users/Gebruiker 1/Dropbox/NUS/Data mining/leagueoflegends')
# laptop:
# setwd('C:/Users/User/Dropbox/NUS/Data mining/leagueoflegends')

# load data file
matches <- read.csv("matches.csv", header=TRUE, sep=",")
```
```{r echo=FALSE, message=FALSE, warning=FALSE, "0.3 Functions"}
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

cuberoot_trans = function() trans_new('cuberoot', 
                                      transform = function(x) x^(1/3), 
                                      inverse = function(x) X^3)


```


```{r echo=FALSE, message=FALSE, warning=FALSE, results = "hide", "0.4 Data Wrangling"}

## 0.4.0 explore a bit

# this runs a whole summary
# summary(matches)
summary(matches$bResult)
names(matches)
# ---> so blue wins more

# 0.4.1 correcting types
for(i in matches){
  print(i, typeof(i))
}


gam$Registration_date <- as.Date(gambl$Registration_date, format = "%m/%d/%Y")

## 0.4.2 making interpretation (and graphs) more easy by adding winner (blue or red) column
matches$winner <- ifelse(matches$bResult > 0, c("blue"), c("red"))




## 0.4.3 making different columns out of each array

# DIFFERENT NEW PROBLEM: CONVERTING 0 TO RG_case:
# names(data_per_age_RG_duration.wide)[names(data_per_age_RG_duration.wide) ==
# '1'] <- 'RG_case'
# names(data_per_age_RG_duration.wide)[names(data_per_age_RG_duration.wide) ==
# '0'] <- 'control'
?substr

## 0.4.3 Dates

# OK I use .dat now, that seems to work, but rest is all set for the .sav file,
# so I choose to import

# FIRST, convert to year
gam$First_Deposit_Year <- as.numeric(str_sub(gambl$First_Deposit_Date, -4, -1))
gam$Registration_Date_Year <- as.numeric(str_sub(gambl$Registration_date, -4, -1))

summary(gam$First_Deposit_Year)
summary(gam$Registration_Date_Year)

# Then date, does not work, maybe missings? --> nope in the .dat file it has a
# lowercase
gam$Registration_date <- as.Date(gambl$Registration_date, format = "%m/%d/%Y")
gam$First_Deposit_Date <- as.Date(gambl$First_Deposit_Date, format = "%m/%d/%Y")

## 0.4.4 Square the data

# https://classroom.udacity.com/nanodegrees/nd002/parts/0021345407/modules/316518875375460/lessons/755618712/concepts/8140986360923

summary(gam$sum_bets_casino)

# +1 is not necessary here due to the exclusion of people that did not make a
# bet in their first month
summary(log10(gam$sum_bets_casino))
summary(sqrt(gam$sum_bets_casino))

# checking the square root variable --> exactly right:
summary(gam$sum_bets_casino_sqrt)
summary(gam$sum_bets_casino)
#--> exactly right:

# +1 is not necessary here due to the exclusion of people that did not make a
# bet in their first month
summary(log10(gam$sum_bets_casino))
summary(sqrt(gam$sum_bets_casino))

```
